name: disks
description: An absolute bare-bones web app.
version: 1.0.0

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: any

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  dart_sass_transformer: any

transformers:
- dart_to_js_script_rewriter
- dart_sass_transformer